inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 120

Lint/UselessAssignment:
  Exclude:
    - 'spec/models/user_spec.rb'

RSpec/EmptyExampleGroup:
  Enabled: false

Airbnb/SimpleModifierConditional:
  Exclude:
    - 'app/models/attendance.rb'
    - 'app/models/collected_shift.rb'
    - 'app/models/concerns/datetime_validators.rb'
    - 'app/models/created_shift.rb'
