inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 120

Lint/UselessAssignment:
  Exclude:
    - 'spec/models/user_spec.rb'
