version: 2.1

jobs:
  build:
    docker:
      - image: sue445/heroku-cli
    steps:
      - checkout
      - build-tools/install-ci-tools
      - jq/install
      - run:
          name: Deploy
          command: git push https://heroku:c384c77c-1e33-4d3e-b0ff-41dbcac335d0@git.heroku.com/app-shift-pote-2020.git develop:master
      - run:
          name: Run post-deploy tasks
          command: |
            heroku run bin/rails db:migrate

orbs:
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@1.9.1