default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRESQL_HOST", "db") %>
  username: <%= ENV.fetch("POSTGRESQL_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRESQL_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  

development:
  <<: *default
  database: shuapp_development

test:
  <<: *default
  database: shuapp_test

production:
  <<: *default
  database: shuapp_production
  username: shuapp
  password: <%= ENV['SHUAPP_DATABASE_PASSWORD'] %>

